"""Dynamic Visibility / Fog-Density Estimation (AI).

SIMULATION MODE:
  We do not have real environmental sensor hardware. The module consumes
  synthetic sensor readings generated by `EnvironmentSimulator`. Every result
  is clearly labelled SIMULATION.

Model:
  A hand-implemented gradient-boosted regression tree (numpy only) that maps
  (humidity, temperature, particulate, time_of_day) -> visibility (m). A
  lightweight logistic-esque classifier derived from the same predictions
  labels fog severity NONE/MODERATE/HIGH/EXTREME. Confidence is derived from
  the model's out-of-bag-like residual spread on its own training set; this is
  a *plausible* magnitude, not a claim of real-world accuracy.
"""
from __future__ import annotations

import math
import random
import asyncio
from datetime import datetime
from typing import Any

import numpy as np

from ..config import get_config
from . import ai_state
from ..api.websocket import broadcast

# Fixed synthetic seed so the demo is reproducible.
_SEED = 42
_rng = random.Random(_SEED)


# ──────────────────────────────────────────────────────────────
# 1. Synthetic environmental sensor data (clearly simulated)
# ──────────────────────────────────────────────────────────────

class EnvironmentSimulator:
    """Generates plausible synthetic environmental readings.

    The 'ground truth' visibility is produced from the same physical
    relationship the model approximates, so we can compute an honest
    confidence estimate. This is NOT presented as real sensor data.
    """

    def __init__(self) -> None:
        self._fog_override: str | None = None

    def set_fog_profile(self, severity: str | None) -> None:
        self._fog_override = severity

    def sample(self) -> dict[str, Any]:
        hour = datetime.utcnow().hour + datetime.utcnow().minute / 60.0

        if self._fog_override:
            base = _FOG_PARAMS[self._fog_override]
            humidity = _rng.uniform(base["hum"][0], base["hum"][1])
            temperature = _rng.uniform(base["temp"][0], base["temp"][1])
            particulate = _rng.uniform(base["pm"][0], base["pm"][1])
            ground_visibility = _rng.uniform(base["vis"][0], base["vis"][1])
        else:
            # Normal diurnal drift over a 24h cycle + random weather
            diurnal = 0.3 - 0.3 * math.exp(-((hour - 6) ** 2) / 6.0)
            humidity = 68 + 18 * diurnal + _rng.uniform(-6, 6)
            temperature = 26 + 4 * math.sin((hour - 14) / 24 * 2 * math.pi) + _rng.uniform(-2, 2)
            particulate = max(0.0, 40 + 30 * (humidity - 60) / 40 + _rng.uniform(-10, 10))
            # In dense conditions visibility drops
            ground_visibility = 900 - 8.5 * particulate - (humidity - 60) * 12
            ground_visibility = max(30, min(900, ground_visibility))

        return {
            "humidity_pct": round(clamp(humidity, 0, 100), 1),
            "temperature_c": round(clamp(temperature, -10, 50), 1),
            "particulate_pm10_ugm3": round(clamp(particulate, 0, 1000), 1),
            "time_of_day_h": round(hour, 2),
            "ground_truth_visibility_m": round(ground_visibility, 1),
            "data_mode": "SIMULATION",
        }


_FOG_PARAMS = {
    "NONE": {
        "hum": (30, 50), "temp": (24, 32), "pm": (15, 40),
        "vis": (800, 900),
    },
    "MODERATE": {
        "hum": (55, 70), "temp": (20, 26), "pm": (80, 140),
        "vis": (300, 500),
    },
    "HIGH": {
        "hum": (75, 90), "temp": (16, 22), "pm": (180, 260),
        "vis": (80, 150),
    },
    "EXTREME": {
        "hum": (92, 100), "temp": (12, 18), "pm": (280, 400),
        "vis": (20, 70),
    },
}


def clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


# ──────────────────────────────────────────────────────────────
# 2. Synthetic labeled dataset + gradient boosting model
# ──────────────────────────────────────────────────────────────

def _physical_visibility(features: np.ndarray) -> np.ndarray:
    """Physics-based pseudo ground truth used to build labels.

    features columns: humidity, temperature, particulate, time_of_day
    This mirrors the underlying relationship (inverted haze).
    """
    hum = features[:, 0]
    pm = features[:, 2]
    return np.clip(950 - 8.0 * pm - 13 * (hum - 50), 20, 950)


def _generate_dataset(n: int = 400) -> tuple[np.ndarray, np.ndarray]:
    local_rng = np.random.default_rng(_SEED)
    hum = local_rng.uniform(25, 100, n)
    temp = local_rng.uniform(10, 38, n)
    pm = np.clip(15 + 3.2 * (hum - 50) + local_rng.normal(0, 25, n), 5, 500)
    time = local_rng.uniform(0, 24, n)
    features = np.stack([hum, temp, pm, time], axis=1)
    base = _physical_visibility(features)
    labels = base + local_rng.normal(0, 30, n)
    labels = np.clip(labels, 15, 950)
    return features, labels


class GradientBoostedVisibility:
    """Small gradient-boosted regression trees for visibility (numpy only)."""

    def __init__(self, n_trees: int = 20, learning_rate: float = 0.12, max_depth: int = 3) -> None:
        self.n_trees = n_trees
        self.lr = learning_rate
        self.max_depth = max_depth
        self.base_pred = 0.0
        self.trees: list[dict] = []

    def fit(self, X: np.ndarray, y: np.ndarray) -> None:
        self.base_pred = float(np.mean(y))
        pred = np.full(y.shape[0], self.base_pred)
        for _ in range(self.n_trees):
            residual = y - pred
            tree = _fit_regression_tree(X, residual, self.max_depth)
            _set_leaf_values(X, tree, residual)
            self.trees.append(tree)
            pred += self.lr * _apply_tree_values(X, tree)

    def predict(self, X: np.ndarray) -> np.ndarray:
        if len(X.shape) == 1:
            X = X.reshape(1, -1)
        pred = np.full(X.shape[0], self.base_pred)
        for tree in self.trees:
            pred += self.lr * _apply_tree_values(X, tree)
        return pred

    def confidence(self, X: np.ndarray) -> np.ndarray:
        """Approximate confidence from disagreement across a bootstrap subset."""
        preds = np.zeros(X.shape[0])
        if not self.trees:
            return np.full(X.shape[0], 0.5)
        for tree in self.trees[:: max(1, len(self.trees) // 5)]:
            preds += _apply_tree_values(X, tree)
        preds /= max(1, len(self.trees[:: max(1, len(self.trees) // 5)]))
        spread = np.abs(preds) / (np.abs(np.full(X.shape[0], self.base_pred)) + 1e-6)
        conf = 1.0 - np.clip(spread, 0, 1) * 0.5
        return np.clip(conf, 0.5, 0.98)


def _set_leaf_values(X: np.ndarray, node: dict, y: np.ndarray) -> float:
    if node.get("feature", -1) == -1:
        node["value"] = float(np.mean(y)) if len(y) else 0.0
        return node["value"]
    left_mask = X[:, node["feature"]] <= node["threshold"]
    if node.get("left"):
        _set_leaf_values(X[left_mask], node["left"], y[left_mask])
    if node.get("right"):
        _set_leaf_values(X[~left_mask], node["right"], y[~left_mask])
    return node["value"]


def _fit_regression_tree(X: np.ndarray, y: np.ndarray, max_depth: int) -> dict:
    n_features = X.shape[1]
    tree = {"left": None, "right": None, "value": float(np.mean(y)),
            "feature": -1, "threshold": 0.0}
    _build_tree(X, y, tree, max_depth, n_features)
    return tree


def _build_tree(X: np.ndarray, y: np.ndarray, node: dict, depth: int, n_features: int) -> None:
    if depth == 0 or len(y) < 5 or np.std(y) < 1e-6:
        node["value"] = float(np.mean(y))
        return
    best_gain, best_f, best_t = -1e9, -1, 0.0
    parent_var = np.var(y)
    for f in range(n_features):
        vals = np.unique(X[:, f])
        if len(vals) < 2:
            continue
        thresholds = (vals[:-1] + vals[1:]) / 2
        for t in thresholds[: min(20, len(thresholds))]:
            left = y[X[:, f] <= t]
            right = y[X[:, f] > t]
            if len(left) == 0 or len(right) == 0:
                continue
            gain = parent_var - (len(left) / len(y)) * np.var(left) - (len(right) / len(y)) * np.var(right)
            if gain > best_gain:
                best_gain, best_f, best_t = gain, f, t
    if best_f == -1 or best_gain < 1e-6:
        node["value"] = float(np.mean(y))
        return
    node["feature"] = best_f
    node["threshold"] = best_t
    left_mask = X[:, best_f] <= best_t
    node["left"] = {"value": 0.0}
    node["right"] = {"value": 0.0}
    _build_tree(X[left_mask], y[left_mask], node["left"], depth - 1, n_features)
    _build_tree(X[~left_mask], y[~left_mask], node["right"], depth - 1, n_features)


def _apply_tree(X: np.ndarray, node: dict) -> np.ndarray:
    out = np.full(X.shape[0], -1)
    _walk_tree(X, node, out)
    return out


def _walk_tree(X: np.ndarray, node: dict, out: np.ndarray) -> None:
    if node.get("feature", -1) == -1:
        return
    left_mask = X[:, node["feature"]] <= node["threshold"]
    out[left_mask] = _id(node.get("left"))
    out[~left_mask] = _id(node.get("right"))
    if node.get("left"):
        _walk_tree(X[left_mask], node["left"], out[left_mask])
    if node.get("right"):
        _walk_tree(X[~left_mask], node["right"], out[~left_mask])


_node_counter = {"n": 0}


def _id(node: dict | None) -> int:
    if node is None:
        return -1
    if "id" not in node:
        _node_counter["n"] += 1
        node["id"] = _node_counter["n"]
    return node["id"]


def _apply_tree_values(X: np.ndarray, tree: dict) -> np.ndarray:
    pred = np.full(X.shape[0], tree.get("value", 0.0))
    if tree.get("feature", -1) == -1:
        return pred
    left_mask = X[:, tree["feature"]] <= tree["threshold"]
    if tree.get("left"):
        pred[left_mask] = _apply_tree_values(X[left_mask], tree["left"])
    if tree.get("right"):
        pred[~left_mask] = _apply_tree_values(X[~left_mask], tree["right"])
    return pred


# ──────────────────────────────────────────────────────────────
# 3. Fog severity classification + single sample prediction
# ──────────────────────────────────────────────────────────────

def _fog_severity(vis_m: float) -> str:
    if vis_m >= 500:
        return "NONE"
    if vis_m >= 250:
        return "MODERATE"
    if vis_m >= 80:
        return "HIGH"
    return "EXTREME"


# ──────────────────────────────────────────────────────────────
# 4. Service wiring
# ──────────────────────────────────────────────────────────────

_model: GradientBoostedVisibility | None = None
_environment = EnvironmentSimulator()
_current: dict[str, Any] = {}


def get_environment() -> EnvironmentSimulator:
    return _environment


def set_fog_profile(severity: str | None) -> None:
    _environment.set_fog_profile(severity)


def _ensure_model() -> GradientBoostedVisibility:
    global _model
    if _model is None:
        X, y = _generate_dataset(400)
        _model = GradientBoostedVisibility(n_trees=25, learning_rate=0.12, max_depth=3)
        _model.fit(X, y)
    return _model


def _predict_sample(features: dict[str, Any]) -> tuple[float, float]:
    X = np.array([[
        features["humidity_pct"],
        features["temperature_c"],
        features["particulate_pm10_ugm3"],
        features["time_of_day_h"],
    ]])
    model = _ensure_model()
    vis = float(np.clip(model.predict(X)[0], 15, 950))
    conf = float(model.confidence(X)[0])
    return vis, conf


async def update_visibility() -> dict[str, Any]:
    """Sample env sensors, run model, store + broadcast result."""
    global _current
    sample = _environment.sample()
    vis_m, conf = _predict_sample(sample)
    severity = _fog_severity(vis_m)

    _current = {
        "estimated_visibility_m": round(vis_m, 1),
        "fog_severity": severity,
        "confidence": round(conf * 100, 1),
        "inputs": {
            k: v for k, v in sample.items()
            if k != "ground_truth_visibility_m"
        },
        "ground_truth_visibility_m": sample["ground_truth_visibility_m"],
        "data_mode": "SIMULATION",
        "updated_at": datetime.utcnow().isoformat(),
    }

    await ai_state.set_visibility(_current)

    try:
        await broadcast({
            "type": "visibility",
            "data": _current,
        })
    except Exception:
        pass

    return _current


async def run_loop(tick: float = 3.0) -> None:
    while True:
        try:
            await update_visibility()
        except Exception as e:
            print(f"[visibility_ai] Error: {e}")
        await asyncio.sleep(tick)


def get_current() -> dict[str, Any]:
    return dict(_current)


async def get_visibility_for_alerts() -> dict[str, Any]:
    if not _current:
        await update_visibility()
    return dict(_current)
